name: merge-ttls
run-name: Merging TTLs
on: [push]
jobs:
  merge-ttl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: find -type f ! -name 'all.ttl' -name '*.ttl' | xargs grep -h '@prefix' | sort -u > all.ttl
      - run: find -type f ! -name 'all.ttl' -name '*.ttl' | xargs grep -vh '@prefix' >> all.ttl